myerr = error.register("my_error")
error.raise(myerr, "testing my own error")
